SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for skillsheet_implants
-- ----------------------------
DROP TABLE IF EXISTS `skillsheet_implants`;
CREATE TABLE `skillsheet_implants` (
  `typeID` int(11) NOT NULL,
  `groupID` int(11) DEFAULT NULL,
  `typeName` varchar(150) NOT NULL,
  `bonus` int(2) NOT NULL,
  PRIMARY KEY (`typeID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of skillsheet_implants
-- ----------------------------
INSERT INTO `skillsheet_implants` VALUES ('2082', '300', 'Genolution Core Augmentation CA-1', '3');
INSERT INTO `skillsheet_implants` VALUES ('2589', '300', 'Genolution Core Augmentation CA-2', '3');
INSERT INTO `skillsheet_implants` VALUES ('9899', '745', 'Ocular Filter - Basic', '3');
INSERT INTO `skillsheet_implants` VALUES ('9941', '745', 'Memory Augmentation - Basic', '3');
INSERT INTO `skillsheet_implants` VALUES ('9942', '745', 'Neural Boost - Basic', '3');
INSERT INTO `skillsheet_implants` VALUES ('9943', '745', 'Cybernetic Subprocessor - Basic', '3');
INSERT INTO `skillsheet_implants` VALUES ('9956', '745', 'Social Adaptation Chip - Basic', '3');
INSERT INTO `skillsheet_implants` VALUES ('10208', '745', 'Memory Augmentation - Standard', '4');
INSERT INTO `skillsheet_implants` VALUES ('10209', '745', 'Memory Augmentation - Improved', '5');
INSERT INTO `skillsheet_implants` VALUES ('10210', '745', 'Memory Augmentation - Advanced', '6');
INSERT INTO `skillsheet_implants` VALUES ('10211', '745', 'Memory Augmentation - Elite', '7');
INSERT INTO `skillsheet_implants` VALUES ('10212', '745', 'Neural Boost - Standard', '4');
INSERT INTO `skillsheet_implants` VALUES ('10213', '745', 'Neural Boost - Improved', '5');
INSERT INTO `skillsheet_implants` VALUES ('10214', '745', 'Neural Boost - Advanced', '6');
INSERT INTO `skillsheet_implants` VALUES ('10215', '745', 'Neural Boost - Elite', '7');
INSERT INTO `skillsheet_implants` VALUES ('10216', '745', 'Ocular Filter - Standard', '4');
INSERT INTO `skillsheet_implants` VALUES ('10217', '745', 'Ocular Filter - Improved', '5');
INSERT INTO `skillsheet_implants` VALUES ('10218', '745', 'Ocular Filter - Advanced', '6');
INSERT INTO `skillsheet_implants` VALUES ('10219', '745', 'Ocular Filter - Elite', '7');
INSERT INTO `skillsheet_implants` VALUES ('10221', '745', 'Cybernetic Subprocessor - Standard', '4');
INSERT INTO `skillsheet_implants` VALUES ('10222', '745', 'Cybernetic Subprocessor - Improved', '5');
INSERT INTO `skillsheet_implants` VALUES ('10223', '745', 'Cybernetic Subprocessor - Advanced', '6');
INSERT INTO `skillsheet_implants` VALUES ('10224', '745', 'Cybernetic Subprocessor - Elite', '7');
INSERT INTO `skillsheet_implants` VALUES ('10225', '745', 'Social Adaptation Chip - Standard', '4');
INSERT INTO `skillsheet_implants` VALUES ('10226', '745', 'Social Adaptation Chip - Improved', '5');
INSERT INTO `skillsheet_implants` VALUES ('10227', '745', 'Social Adaptation Chip - Advanced', '6');
INSERT INTO `skillsheet_implants` VALUES ('13283', '745', 'Limited Ocular Filter', '1');
INSERT INTO `skillsheet_implants` VALUES ('13284', '745', 'Limited Memory Augmentation', '1');
INSERT INTO `skillsheet_implants` VALUES ('13285', '745', 'Limited Neural Boost', '1');
INSERT INTO `skillsheet_implants` VALUES ('13286', '745', 'Limited Social Adaptation Chip', '1');
INSERT INTO `skillsheet_implants` VALUES ('13287', '745', 'Limited Cybernetic Subprocessor', '1');
INSERT INTO `skillsheet_implants` VALUES ('14295', '745', 'Limited Ocular Filter - Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('14296', '745', 'Limited Neural Boost - Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('14297', '745', 'Limited Memory Augmentation - Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('14298', '745', 'Limited Cybernetic Subprocessor - Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('14299', '745', 'Limited Social Adaptation Chip - Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('19534', '300', 'High-grade Talisman Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('19535', '300', 'High-grade Talisman Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('19536', '300', 'High-grade Talisman Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('19537', '300', 'High-grade Talisman Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('19538', '300', 'High-grade Talisman Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('19539', '300', 'High-grade Talisman Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('19540', '300', 'High-grade Snake Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('19551', '300', 'High-grade Snake Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('19553', '300', 'High-grade Snake Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('19554', '300', 'High-grade Snake Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('19555', '300', 'High-grade Snake Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('19556', '300', 'High-grade Snake Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('20121', '300', 'High-grade Crystal Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('20157', '300', 'High-grade Crystal Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('20158', '300', 'High-grade Crystal Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('20159', '300', 'High-grade Crystal Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('20160', '300', 'High-grade Crystal Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('20161', '300', 'High-grade Crystal Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('20498', '300', 'High-grade Halo Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('20499', '300', 'High-grade Slave Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('20500', '300', 'High-grade Halo Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('20501', '300', 'High-grade Slave Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('20502', '300', 'High-grade Halo Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('20503', '300', 'High-grade Slave Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('20504', '300', 'High-grade Halo Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('20505', '300', 'High-grade Slave Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('20506', '300', 'High-grade Halo Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('20507', '300', 'High-grade Slave Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('20508', '300', 'High-grade Halo Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('20509', '300', 'High-grade Slave Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('22107', '300', 'Mid-grade Crystal Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('22108', '300', 'Mid-grade Crystal Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22109', '300', 'Mid-grade Crystal Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22110', '300', 'Mid-grade Crystal Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('22111', '300', 'Mid-grade Crystal Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('22112', '300', 'Mid-grade Crystal Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('22113', '300', 'Mid-grade Halo Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('22114', '300', 'Mid-grade Halo Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22115', '300', 'Mid-grade Halo Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22116', '300', 'Mid-grade Halo Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('22117', '300', 'Mid-grade Halo Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('22118', '300', 'Mid-grade Halo Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('22119', '300', 'Mid-grade Slave Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('22120', '300', 'Mid-grade Slave Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22121', '300', 'Mid-grade Slave Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22122', '300', 'Mid-grade Slave Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('22123', '300', 'Mid-grade Slave Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('22124', '300', 'Mid-grade Slave Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('22125', '300', 'Mid-grade Snake Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('22126', '300', 'Mid-grade Snake Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22127', '300', 'Mid-grade Snake Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22128', '300', 'Mid-grade Snake Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('22129', '300', 'Mid-grade Snake Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('22130', '300', 'Mid-grade Snake Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('22131', '300', 'Mid-grade Talisman Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('22133', '300', 'Mid-grade Talisman Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22134', '300', 'Mid-grade Talisman Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('22135', '300', 'Mid-grade Talisman Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('22136', '300', 'Mid-grade Talisman Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('22137', '300', 'Mid-grade Talisman Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('28790', '300', 'Mid-grade Centurion Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('28791', '300', 'Mid-grade Centurion Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28792', '300', 'Mid-grade Centurion Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28793', '300', 'Mid-grade Centurion Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('28794', '300', 'Mid-grade Centurion Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('28795', '300', 'Mid-grade Centurion Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('28796', '300', 'Mid-grade Nomad Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('28797', '300', 'Mid-grade Nomad Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28798', '300', 'Mid-grade Nomad Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28799', '300', 'Mid-grade Nomad Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('28800', '300', 'Mid-grade Nomad Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('28801', '300', 'Mid-grade Nomad Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('28802', '300', 'Mid-grade Harvest Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('28803', '300', 'Mid-grade Harvest Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28804', '300', 'Mid-grade Harvest Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28805', '300', 'Mid-grade Harvest Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('28806', '300', 'Mid-grade Harvest Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('28807', '300', 'Mid-grade Harvest Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('28808', '300', 'Mid-grade Virtue Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('28809', '300', 'Mid-grade Virtue Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28810', '300', 'Mid-grade Virtue Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28811', '300', 'Mid-grade Virtue Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('28812', '300', 'Mid-grade Virtue Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('28813', '300', 'Mid-grade Virtue Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('28814', '300', 'Mid-grade Edge Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('28815', '300', 'Mid-grade Edge Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28816', '300', 'Mid-grade Edge Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('28817', '300', 'Mid-grade Edge Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('28818', '300', 'Mid-grade Edge Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('28819', '300', 'Mid-grade Edge Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('31954', '300', 'High-grade Grail Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('31955', '300', 'High-grade Grail Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31956', '300', 'High-grade Grail Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31957', '300', 'High-grade Grail Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('31958', '300', 'High-grade Grail Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('31959', '300', 'High-grade Grail Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('31962', '300', 'High-grade Talon Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('31963', '300', 'High-grade Talon Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31964', '300', 'High-grade Talon Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31965', '300', 'High-grade Talon Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('31966', '300', 'High-grade Talon Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('31967', '300', 'High-grade Talon Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('31968', '300', 'High-grade Spur Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('31969', '300', 'High-grade Spur Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31970', '300', 'High-grade Spur Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31971', '300', 'High-grade Spur Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('31972', '300', 'High-grade Spur Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('31973', '300', 'High-grade Spur Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('31974', '300', 'High-grade Jackal Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('31975', '300', 'High-grade Jackal Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31976', '300', 'High-grade Jackal Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('31977', '300', 'High-grade Jackal Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('31978', '300', 'High-grade Jackal Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('31979', '300', 'High-grade Jackal Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('32101', '300', 'Low-grade Grail Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('32102', '300', 'Low-grade Grail Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32103', '300', 'Low-grade Grail Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32104', '300', 'Low-grade Grail Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('32105', '300', 'Low-grade Grail Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('32107', '300', 'Low-grade Spur Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('32108', '300', 'Low-grade Spur Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32109', '300', 'Low-grade Spur Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32110', '300', 'Low-grade Spur Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('32111', '300', 'Low-grade Spur Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('32112', '300', 'Low-grade Talon Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('32113', '300', 'Low-grade Talon Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32114', '300', 'Low-grade Talon Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32115', '300', 'Low-grade Talon Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('32116', '300', 'Low-grade Talon Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('32117', '300', 'Low-grade Jackal Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('32118', '300', 'Low-grade Jackal Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32119', '300', 'Low-grade Jackal Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('32120', '300', 'Low-grade Jackal Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('32121', '300', 'Low-grade Jackal Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('32122', '300', 'Low-grade Grail Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('32123', '300', 'Low-grade Jackal Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('32124', '300', 'Low-grade Spur Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('32125', '300', 'Low-grade Talon Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33393', '300', 'Genolution Core Augmentation CA-3', '3');
INSERT INTO `skillsheet_implants` VALUES ('33394', '300', 'Genolution Core Augmentation CA-4', '3');
INSERT INTO `skillsheet_implants` VALUES ('33516', '300', 'High-grade Ascendancy Alpha', '4');
INSERT INTO `skillsheet_implants` VALUES ('33525', '300', 'High-grade Ascendancy Beta', '4');
INSERT INTO `skillsheet_implants` VALUES ('33526', '300', 'High-grade Ascendancy Delta', '4');
INSERT INTO `skillsheet_implants` VALUES ('33527', '300', 'High-grade Ascendancy Epsilon', '4');
INSERT INTO `skillsheet_implants` VALUES ('33528', '300', 'High-grade Ascendancy Gamma', '4');
INSERT INTO `skillsheet_implants` VALUES ('33529', '300', 'High-grade Ascendancy Omega', '4');
INSERT INTO `skillsheet_implants` VALUES ('33555', '300', 'Mid-grade Ascendancy Alpha', '3');
INSERT INTO `skillsheet_implants` VALUES ('33557', '300', 'Mid-grade Ascendancy Beta', '3');
INSERT INTO `skillsheet_implants` VALUES ('33559', '300', 'Mid-grade Ascendancy Delta', '3');
INSERT INTO `skillsheet_implants` VALUES ('33561', '300', 'Mid-grade Ascendancy Epsilon', '3');
INSERT INTO `skillsheet_implants` VALUES ('33563', '300', 'Mid-grade Ascendancy Gamma', '3');
INSERT INTO `skillsheet_implants` VALUES ('33565', '300', 'Mid-grade Ascendancy Omega', '3');
INSERT INTO `skillsheet_implants` VALUES ('33807', '300', 'Cybernetic \'Source\' Subprocessor', '4');
INSERT INTO `skillsheet_implants` VALUES ('33808', '300', 'Neural \'Source\' Boost', '4');
INSERT INTO `skillsheet_implants` VALUES ('33917', '300', 'Low-grade Centurion Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33918', '300', 'Low-grade Centurion Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33919', '300', 'Low-grade Centurion Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33920', '300', 'Low-grade Centurion Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33921', '300', 'Low-grade Centurion Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33922', '300', 'Low-grade Centurion Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33923', '300', 'Low-grade Crystal Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33924', '300', 'Low-grade Crystal Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33925', '300', 'Low-grade Crystal Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33926', '300', 'Low-grade Crystal Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33927', '300', 'Low-grade Crystal Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33928', '300', 'Low-grade Crystal Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33929', '300', 'Low-grade Edge Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33930', '300', 'Low-grade Edge Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33931', '300', 'Low-grade Edge Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33932', '300', 'Low-grade Edge Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33933', '300', 'Low-grade Edge Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33934', '300', 'Low-grade Edge Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33935', '300', 'Low-grade Halo Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33936', '300', 'Low-grade Halo Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33937', '300', 'Low-grade Halo Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33938', '300', 'Low-grade Halo Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33939', '300', 'Low-grade Halo Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33940', '300', 'Low-grade Halo Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33941', '300', 'Low-grade Harvest Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33942', '300', 'Low-grade Harvest Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33943', '300', 'Low-grade Harvest Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33944', '300', 'Low-grade Harvest Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33945', '300', 'Low-grade Harvest Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33946', '300', 'Low-grade Harvest Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33947', '300', 'Low-grade Nomad Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33948', '300', 'Low-grade Nomad Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33949', '300', 'Low-grade Nomad Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33950', '300', 'Low-grade Nomad Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33951', '300', 'Low-grade Nomad Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33952', '300', 'Low-grade Nomad Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33953', '300', 'Low-grade Slave Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33954', '300', 'Low-grade Slave Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33955', '300', 'Low-grade Slave Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33956', '300', 'Low-grade Slave Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33957', '300', 'Low-grade Slave Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33958', '300', 'Low-grade Slave Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33959', '300', 'Low-grade Snake Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33960', '300', 'Low-grade Snake Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33961', '300', 'Low-grade Snake Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33962', '300', 'Low-grade Snake Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33963', '300', 'Low-grade Snake Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33964', '300', 'Low-grade Snake Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33965', '300', 'Low-grade Talisman Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33966', '300', 'Low-grade Talisman Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33967', '300', 'Low-grade Talisman Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33968', '300', 'Low-grade Talisman Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33969', '300', 'Low-grade Talisman Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33970', '300', 'Low-grade Talisman Omega', '2');
INSERT INTO `skillsheet_implants` VALUES ('33971', '300', 'Low-grade Virtue Alpha', '2');
INSERT INTO `skillsheet_implants` VALUES ('33972', '300', 'Low-grade Virtue Beta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33973', '300', 'Low-grade Virtue Delta', '2');
INSERT INTO `skillsheet_implants` VALUES ('33974', '300', 'Low-grade Virtue Epsilon', '2');
INSERT INTO `skillsheet_implants` VALUES ('33975', '300', 'Low-grade Virtue Gamma', '2');
INSERT INTO `skillsheet_implants` VALUES ('33976', '300', 'Low-grade Virtue Omega', '2');